---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: backend
  namespace: app
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  metrics:
    - type: Resource
      resource:
        name: memory
