---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
  namespace: app
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: srv
          image: 'nginx:alpine'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '0.5'
              memory: 512Mi
          imagePullPolicy: IfNotPresent
          startupProbe:
            exec:
              command:
                - curl
                - http://localhost:8080/metrics
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
              scheme: HTTP
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
              scheme: HTTP
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 10
      restartPolicy: Always
