---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: app
  labels:
    app: mysql
data:
  my.cnf: |
    [mysql]
    
    default-character-set=utf8mb4
    
    [client]
    
    default-character-set=utf8mb4
    
    [mysqld]

    bind-address=0.0.0.0
    
    max_connections=1000
    
    table_open_cache=4096
    
    default_time_zone=Asia/Shanghai
    
    character-set-server=utf8mb4
    
    collation-server=utf8mb4_unicode_ci
    
    log-error=/var/log/mysql/error.log
    
    secure_file_priv=/var/lib/mysql
    
    default-authentication-plugin=caching_sha2_password
    
    sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    
    # log.slow
    
    slow_query_log=1
    
    long_query_time=2
    
    slow_query_log_file=/var/log/mysql/slow.log
    
    # tmp table
    
    tmp_table_size=128M
    
    max_heap_table_size=128M

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: '10.64.10.210:10083/mysql:8'
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 1qaz!QAZ
          ports:
            - containerPort: 3306
              name: tcp
              protocol: TCP
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /var/lib/mysql
              name: data
            - mountPath: /etc/mysql/my.cnf
              name: config
              subPath: my.cnf
#        - name: metrics
#          image: '10.64.21.107:83/prom/mysqld-exporter:v0.14.0'
#          imagePullPolicy: IfNotPresent
#          env:
#            - name: DATA_SOURCE_NAME
#              value: "user:password@(localhost:3306)/database"
#          ports:
#            - containerPort: 9104
#              name: tcp
#              protocol: TCP
#          resources:
#            limits:
#              cpu: '0.2'
#              memory: 256Mi
#            requests:
#              cpu: '0.1'
#              memory: 128Mi
      nodeSelector:
        map: "true"
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: mysql
          name: config
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: ""
          name: localtime
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Ti
        storageClassName: rook
        volumeMode: Filesystem

---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: app
  labels:
    app: mysql
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
#    - name: metrics
#      protocol: TCP
#      port: 9104
#      targetPort: 9104
  selector:
    app: mysql
  type: ClusterIP
