version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    user: root
    privileged: true
    ports:
      - "2181:2181"
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /opt/volumes/broker/zookeeper:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    restart: always
    user: root
    privileged: true
    ports:
      - "9092:9092"
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /opt/volumes/broker/kafka/data:/bitnami/kafka/data
#      - /opt/volumes/broker/kafka/config:/opt/bitnami/kafka/config
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

networks:
  default:
    name: local