version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    hostname: mysql
    restart: always
    user: root
    privileged: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - /opt/volumes/mysql/data:/var/lib/mysql
      - /opt/volumes/mysql/conf.d:/etc/mysql/conf.d

networks:
  default:
    name: local
